title: 'hunterwarbs.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/hunterthoughts"
url: "https://hunterwarbs.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: '<a href="https://instagram.com/hunterwarbs">photos</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
