title: 'huntersthoughts'
description: "A place for my thoughts."
baseurl: "/"
url: "https://hunterwarbs.github.io"

style: dark

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
